/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jswingpractica1;

import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author DarkGirl
 */
public class JFramePractica1 extends javax.swing.JFrame {

    /**
     * Creates new form JFramePractica1
     */
    public JFramePractica1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldDivisa1 = new javax.swing.JTextField();
        jTextFieldDivisa2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor De Divisas");
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(50, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText(">");
        jButton1.setActionCommand("btnDivisa1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("<");
        jButton2.setActionCommand("btnDivisa2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextFieldDivisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDivisa1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Edilma Alvarado Espinoza y Levi Malet  - Práctica 1 DIU -");

        jLabel2.setText("Cantidad");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("dolar > euro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(74, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDivisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jTextFieldDivisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void jTextFieldDivisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDivisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDivisa1ActionPerformed

    private String changeToTwoDigits(Double number){
        return new DecimalFormat("#.00").format(number).toString();
    }
    
    private boolean numberNotEmpty(String text){
        return !text.isEmpty();
    }
    
    private boolean isPositiveNumber (Double number){
        return (number >= 0);
    }
    
    private boolean isNumber(String text){
        for (int i = 0; i < text.length(); i++) {
            if(Character.isLetter(text.charAt(i))) return true;
        }
        return false;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if(  numberNotEmpty(jTextField1.getText()) && !numberNotEmpty(jTextFieldDivisa1.getText()) || !numberNotEmpty(jTextField1.getText()) && numberNotEmpty(jTextFieldDivisa1.getText()) ){
                throw new Exception("Introduce un valor numérico en los dos campos");
            }
            else if(!numberNotEmpty(jTextFieldDivisa1.getText()) && !numberNotEmpty(jTextField1.getText())) throw new Exception("Introduce un valor numérico en los dos campos");
            
            else if( isNumber(jTextField1.getText()) && isNumber(jTextFieldDivisa1.getText())) throw new Exception("Introduce valores numericos");
            
            else if( !isNumber(jTextField1.getText()) && isNumber(jTextFieldDivisa1.getText()) || isNumber(jTextField1.getText()) && !isNumber(jTextFieldDivisa1.getText()) ) throw new Exception("Introduce valores numericos");
            
            else if( !isPositiveNumber(Double.parseDouble(jTextField1.getText())) && isPositiveNumber(Double.parseDouble(jTextFieldDivisa1.getText()))) throw new Exception("Introducir valores Positivos");
            
            else if( isPositiveNumber(Double.parseDouble(jTextField1.getText())) && !isPositiveNumber(Double.parseDouble(jTextFieldDivisa1.getText()))) throw new Exception("Introducir valores Positivos");
            
            else if( !isPositiveNumber(Double.parseDouble(jTextField1.getText())) && !isPositiveNumber(Double.parseDouble(jTextFieldDivisa1.getText()))) throw new Exception("Introducir valores Positivos");
            
            else{
                Double result = Double.parseDouble(jTextField1.getText()) * Double.parseDouble(jTextFieldDivisa1.getText()) ;
                jTextFieldDivisa2.setText(changeToTwoDigits(result)+ "" );
                jLabel4.setText("dolar > euro");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());  
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            if(  numberNotEmpty(jTextField1.getText()) && !numberNotEmpty(jTextFieldDivisa2.getText()) || !numberNotEmpty(jTextField1.getText()) && numberNotEmpty(jTextFieldDivisa2.getText()) ){
                throw new Exception("Introduce un valor numérico en los dos campos");
            }
            else if(!numberNotEmpty(jTextFieldDivisa1.getText()) && !numberNotEmpty(jTextField1.getText())) throw new Exception("Introduce un valor numérico en los dos campos");
            
            else if( isNumber(jTextField1.getText()) && isNumber(jTextFieldDivisa2.getText())) throw new Exception("Introduce valores numericos");
            
            else if( !isNumber(jTextField1.getText()) && isNumber(jTextFieldDivisa2.getText()) || isNumber(jTextField1.getText()) && !isNumber(jTextFieldDivisa2.getText()) ) throw new Exception("Introduce valores numericos");
            
            else if( !isPositiveNumber(Double.parseDouble(jTextField1.getText())) && isPositiveNumber(Double.parseDouble(jTextFieldDivisa2.getText()))) throw new Exception("Introducir valores Positivos");
            
            else if( isPositiveNumber(Double.parseDouble(jTextField1.getText())) && !isPositiveNumber(Double.parseDouble(jTextFieldDivisa2.getText()))) throw new Exception("Introducir valores Positivos");
            
            else if( !isPositiveNumber(Double.parseDouble(jTextField1.getText())) && !isPositiveNumber(Double.parseDouble(jTextFieldDivisa2.getText()))) throw new Exception("Introducir valores Positivos");
            
            else{
                Double result = Double.parseDouble(jTextField1.getText()) * Double.parseDouble(jTextFieldDivisa2.getText()) ;
                jTextFieldDivisa1.setText(changeToTwoDigits(result)+ "" );
                jLabel4.setText("dolar < euro");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePractica1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePractica1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldDivisa1;
    private javax.swing.JTextField jTextFieldDivisa2;
    // End of variables declaration//GEN-END:variables
}
